# Generated by Django 4.2 on 2023-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flights_destination_alter_flights_origin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
    ]
